;
; +-------------------------------------------------------------------------+
; |     This file is generated by The Interactive Disassembler (IDA)        |
; |     Copyright (c) 2003 by DataRescue sa/nv, <ida@datarescue.com>        |
; |  Licensed to: Michael Wolski - Personal Use (1-user Standard 07/2003)   |
; +-------------------------------------------------------------------------+
;

; Processor:        68000
; Target Assembler: 680x0 Assembler in MRI compatible mode
; This file should be compiled with "as -M"

; ---------------------------------------------------------------------------
		cpu 68000
		include "sonic3k.macrosetup.asm"	; include a few basic macros
		include "sonic3k.macros.asm"		; include some simplifying macros and functions
		include "sonic3k.constants.asm"		; include some constants
		include "s3.constants.asm"		; RAM addresses moved around between S3 and S&K
; ---------------------------------------------------------------------------
; Include SMPS2ASM, for expressing SMPS bytecode in a portable and human-readable form.
FixMusicAndSFXDataBugs = 0
SonicDriverVer = 3 ; Tell SMPS2ASM that we are targeting Sonic 3's sound driver
		include "Sound/_smps2asm_inc.asm"

Size_of_Snd_driver_guess = $1300
Size_of_Snd_driver2_guess = $843
Size_of_Snd_Bank1 = $E60
; This particular bank has its contents aligned to the end
; ---------------------------------------------------------------------------

StartOfROM:
	if * <> 0
		fatal "StartOfROM was $\{*} but it should be 0"
	endif

		; According to Sonic Jam, this is the 'AC' segment.
		include "code S3/Header, EntryPoint.asm"
		include "code S3/Int.asm" ; Likely the actual filename in the original source code, according to the Yuji Naka footage

		; General
		include "code S3/Utilities.asm"
		include "code S3/Utilities2.asm"

; ---------------------------------------------------------------------------

		include "code S3/subsystems/Palette.asm"

; ---------------------------------------------------------------------------

		; Screen modes
		include "code S3/modes/Sega Screen.asm"

; ---------------------------------------------------------------------------

		include "code S3/modes/Title Screen.asm"

; ---------------------------------------------------------------------------

		include "code S3/modes/Level.asm"

; ---------------------------------------------------------------------------

		include "code S3/modes/Options Screen & Level Select.asm"

; ---------------------------------------------------------------------------

		include "code S3/modes/Special Stage.asm"

; ---------------------------------------------------------------------------

		include "code S3/modes/Competition.asm"

; ---------------------------------------------------------------------------

		include "code S3/modes/Save Screen.asm"

; ---------------------------------------------------------------------------

		include "code S3/subsystems/hud.asm"

		include "code S3/subsystems/Rings.asm"

		include "code S3/subsystems/Bumpers.asm"

		include "code S3/subsystems/collision.asm"

		include "code S3/subsystems/floor and wall distance checking.asm"

		include "code S3/subsystems/player enemy collision.asm"

; ---------------------------------------------------------------------------

		include "code S3/objects/Sonic.asm"

; ---------------------------------------------------------------------------

		include "code S3/objects/Tails.asm"

; ---------------------------------------------------------------------------

		include "code S3/objects/Drowning Bubbles, Shields, Splash, Super Sonic Stars.asm"

; ---------------------------------------------------------------------------

		include "code S3/objects/Rings.asm"

; ---------------------------------------------------------------------------

		include "code S3/subsystems/Objects.asm"

; ---------------------------------------------------------------------------

		include "code S3/subsystems/Object Loader.asm"

; ---------------------------------------------------------------------------

		include "code S3/subsystems/Level Data & Drawing.asm"

; ---------------------------------------------------------------------------

		include "code S3/subsystems/Resize.asm"

; ---------------------------------------------------------------------------

		include "code S3/objects/LRZ Rocks.asm"

; ---------------------------------------------------------------------------

		include "code S3/objects/Path Swapper.asm"

; ---------------------------------------------------------------------------

		include "code S3/objects/Monitor.asm"

; ---------------------------------------------------------------------------

		include "code S3/subsystems/player solid object collision.asm"

; ---------------------------------------------------------------------------

		include "code S3/objects/Explosion.asm"

; ---------------------------------------------------------------------------

		include "code S3/objects/objects.asm"

; ---------------------------------------------------------------------------

		include "code S3/subsystems/animated level artwork.asm"

; ---------------------------------------------------------------------------

		include "code S3/objects/objects2.asm"

; ---------------------------------------------------------------------------

		include "code S3/objects/objects3.asm"

; ---------------------------------------------------------------------------

		include "code S3/subsystems/Level Events.asm"

; ---------------------------------------------------------------------------

		include "code S3/modes/Continue Screen.asm"

; ---------------------------------------------------------------------------

		include "code S3/modes/S3 Credits.asm"

; ---------------------------------------------------------------------------

		include "code S3/modes/S2 Sega Screen.asm"

; ---------------------------------------------------------------------------

		include "code S3/Gumball.asm"

; ---------------------------------------------------------------------------

		include "code S3/objects/Giant Ring.asm"

; ---------------------------------------------------------------------------

		include "code S3/objects/Knuckles NPC.asm"

; ---------------------------------------------------------------------------

		include "code S3/objects/Robotnik.asm"

; ---------------------------------------------------------------------------

		include "code S3/objects/Boss.asm"

; ---------------------------------------------------------------------------

		include "code S3/objects/Signpost.asm"

; ---------------------------------------------------------------------------

		include "code S3/subsystems/Boss Defeat.asm"

; ---------------------------------------------------------------------------

		include "code S3/objects/almighty object blob.asm"

; ---------------------------------------------------------------------------

		include "code S3/objects/Egg Capsule.asm"

; ---------------------------------------------------------------------------

		include "code S3/objects/Badnik.asm"

; ---------------------------------------------------------------------------

		; Subsystems again
		include "code S3/subsystems/plcs.asm"
		include "code S3/subsystems/edit.asm" ; Likely the actual filename in the original source code, according to the Yuji Naka footage

Sprite_Listing:
		include "Levels/Misc/Object pointers - S3 Set.asm"

		align $2000

Character_Speeds:
		dc.w  $600,  $10,  $20,    0
		dc.w  $4C0,  $1C,  $70,    0
		dc.w  $580,  $10, $200,    0

		include "code S3/assets/Layouts.asm"

		align $1000
		; According to Sonic Jam, this is the 'TBL' segment.
		include "code S3/assets/assets.asm"

		align0 $20

		include "code S3/assets/assets2.asm"

		include "code S3/assets/Sound.asm"

		align $1000

		include "Sound/Z80 Sound Driver.asm"

		include "code S3/assets/Sound2.asm"

		align $8000

		include "code S3/assets/assets3.asm"

		align $100

		include "code S3/assets/assets4.asm"

Pachinko_16x16_Kos:
ArtKosM_Pachinko:
Pachinko_128x128_Kos:
Slots_16x16_Kos:
ArtKosM_Slots:
Slots_128x128_Kos:
		org $200000

EndOfROM:
		END
