;
; ---------------------------------------------------------------------------
; ║     This file is generated by The Interactive Disassembler (IDA)        ║
; ║     Copyright (c) 2003 by DataRescue sa/nv, <ida@datarescue.com>        ║
; ║  Licensed to: Michael Wolski - Personal Use (1-user Standard 07/2003)   ║
; ---------------------------------------------------------------------------
;
; File Name   :	C:\SKDisasm\SONICNUC.BIN
; Format      :	Binary File
; Base Address:	0000h Range: 0000h - 200000h Loaded length: 200000h
;
; 2006-12-31 - Original buildable disassembly, labeling, and formatting by Stealth
; Please list any revisions

; Processor:        68000
; Target Assembler: 680x0 Assembler in MRI compatible mode
; This file should be compiled with "as -M"

; ---------------------------------------------------------------------------
		cpu 68000
		include "sonic3k.macrosetup.asm"	; include a few basic macros
		include "sonic3k.macros.asm"		; include some simplifying macros and functions
		include "sonic3k.constants.asm"		; include some constants
; ---------------------------------------------------------------------------
; Include SMPS2ASM, for expressing SMPS bytecode in a portable and human-readable form.
FixMusicAndSFXDataBugs = 0
SonicDriverVer = 4 ; Tell SMPS2ASM that we are targeting Sonic & Knuckles' sound driver
		include "Sound/_smps2asm_inc.asm"
; ---------------------------------------------------------------------------
; Assembly options:

; 'Sonic3_Complete' is set via build scripts to 0 or 1.
; If 1, includes all required Sonic 3 data in order to assemble a smaller version of S3K (with all redundancies removed)

strip_padding = 0|Sonic3_Complete
; If 1, strips all unnecessary padding

Size_of_Snd_driver_guess = $E00
Size_of_Snd_driver2_guess = $690
; Approximate size of compressed sound driver. Change when appropriate

Size_of_Snd_Bank1 = $3EFC
; This particular bank has its contents aligned to the end
; ---------------------------------------------------------------------------

StartOfROM:
	if * <> 0
		fatal "StartOfROM was $\{*} but it should be 0"
	endif

		; According to Sonic Jam, this is the 'AC' segment.
		include "code/Header, EntryPoint.asm"
		include "code/Int.asm" ; Likely the actual filename in the original source code, according to the Yuji Naka footage

		; General
		include "code/Utilities.asm"
		include "code/Utilities2.asm"

; ---------------------------------------------------------------------------

		include "code/subsystems/Palette.asm"

; ---------------------------------------------------------------------------

		; Screen modes
		include "code/modes/Sega Screen.asm"

; ---------------------------------------------------------------------------

		include "code/modes/Title Screen.asm"

; ---------------------------------------------------------------------------

		include "code/modes/Level.asm"

; ---------------------------------------------------------------------------

		include "code/modes/Level Select.asm"

; ---------------------------------------------------------------------------

		include "code/modes/Special Stage.asm"

; ---------------------------------------------------------------------------

		include "code/modes/Competition.asm"

; ---------------------------------------------------------------------------

		include "code/modes/Save Screen.asm"

; ---------------------------------------------------------------------------


		include "code/subsystems/hud.asm"

		include "code/subsystems/Rings.asm"

		include "code/subsystems/collision.asm"

		include "code/subsystems/floor and wall distance checking.asm"

		include "code/subsystems/player enemy collision.asm"

; ---------------------------------------------------------------------------

		include "code/objects/Sonic.asm"

; ---------------------------------------------------------------------------

		include "code/objects/Tails.asm"

; ---------------------------------------------------------------------------

		include "code/objects/Knuckles.asm"

; ---------------------------------------------------------------------------

		include "code/objects/Drowning Bubbles, Shields, Splash, Super Sonic Stars.asm"

; ---------------------------------------------------------------------------

		include "code/objects/Rings.asm"

; ---------------------------------------------------------------------------

		include "code/subsystems/Objects.asm"

; ---------------------------------------------------------------------------

		include "code/subsystems/Object Loader.asm"

; ---------------------------------------------------------------------------

		include "code/subsystems/Level Data & Drawing.asm"

; ---------------------------------------------------------------------------

		include "code/subsystems/Resize.asm"

; ---------------------------------------------------------------------------

		include "code/objects/LRZ Rocks.asm"

; ---------------------------------------------------------------------------

		include "code/objects/Path Swapper.asm"

; ---------------------------------------------------------------------------

		include "code/objects/Monitor.asm"

; ---------------------------------------------------------------------------

		include "code/subsystems/player solid object collision.asm"

; ---------------------------------------------------------------------------

		include "code/objects/Explosion.asm"

; ---------------------------------------------------------------------------

		include "code/objects/objects.asm"

; ---------------------------------------------------------------------------

		include "code/subsystems/animated level artwork.asm"

; ---------------------------------------------------------------------------

		include "code/objects/objects2.asm"

; ---------------------------------------------------------------------------

		include "code/objects/objects3.asm"

; ---------------------------------------------------------------------------

		include "code/modes/Blue Sphere.asm"

; ---------------------------------------------------------------------------

		include "code/subsystems/Level Events.asm"

; ---------------------------------------------------------------------------

		include "code/modes/Credits.asm"

; ---------------------------------------------------------------------------

		include "code/modes/Continue Screen.asm"

; ---------------------------------------------------------------------------

		include "code/modes/S3 Credits.asm"

; ---------------------------------------------------------------------------

		include "code/modes/Ending.asm"

; ---------------------------------------------------------------------------

		include "code/objects/Gumball/Objects.asm"

; ---------------------------------------------------------------------------

		include "code/objects/Giant Ring.asm"

; ---------------------------------------------------------------------------

		include "code/objects/Knuckles NPC.asm"

; ---------------------------------------------------------------------------

		include "code/objects/Robotnik.asm"

; ---------------------------------------------------------------------------

		include "code/objects/Boss.asm"

; ---------------------------------------------------------------------------

		include "code/objects/Signpost.asm"

; ---------------------------------------------------------------------------

		include "code/subsystems/Boss Defeat.asm"

; ---------------------------------------------------------------------------

		include "code/objects/almighty object blob.asm"

; ---------------------------------------------------------------------------

		include "code/objects/Egg Capsule.asm"

; ---------------------------------------------------------------------------

		include "code/objects/Badnik.asm"

; ---------------------------------------------------------------------------

		; Subsystems again
		include "code/subsystems/plcs.asm"
		include "code/subsystems/edit.asm" ; Likely the actual filename in the original source code, according to the Yuji Naka footage

Sprite_Listing3:
		include "Levels/Misc/Object pointers - SK Set 1.asm"
Sprite_ListingK:
		include "Levels/Misc/Object pointers - SK Set 2.asm"

	if ~~strip_padding
		align $1000
	else
		even
	endif

		; According to Sonic Jam, this is the 'TBL' segment.
		include "code/assets/assets.asm"

	if ~~strip_padding
		cnop0 -$40,$100
	endif

		; According to Sonic Jam, this is the 'DATA' segment.
		include "code/assets/assets2.asm"

	if ~~strip_padding
		cnop -$600,$1000
	endif

ArtNem_KnuxEndPose:
		binclude "General/Ending/Nemesis Art/Knuckles Ending Pose.bin"
		even

		; According to Sonic Jam, this is the 'ACTTBL' segment.
		include "code/assets/KIS2 Object Layouts.asm"

		include "code/assets/Sound.asm"

	if ~~strip_padding
		align $10
	else
		even
	endif

		include "Sound/Z80 Sound Driver.asm"

		include "code/assets/Sound2.asm"

	if ~~strip_padding
		align $8000
	else
		even
	endif

		include "code/assets/assets3.asm"

	if ~~strip_padding
		align $100
	endif

		include "code/assets/assets4.asm"

	if ~~strip_padding
		align $100
	else
		even
	endif

Character_Speeds:
		dc.w  $600,  $10,  $20,    0		; Sonic
		dc.w  $4C0,  $1C,  $70,    0		; Tails
		dc.w  $580,  $10, $200,    0		; Knuckles

		include "code/assets/Layouts.asm"

	; AS would automatically strip this padding if we didn't specifically declare one byte at the end
	if ~~strip_padding && (*)&(*-1)
		cnop -1,2<<lastbit(*)
		dc.b $FF
	else
		even
	endif

	if Sonic3_Complete=0
EndOfROM:
		org $200000	; needed if you want to combine the ROM with Sonic 3 or Sonic 2 and the UPMEM
		include "Lockon S3/LockOn Pointers.asm"
	else
		include "Lockon S3/LockOn Data.asm"
EndOfROM:
	endif

		END
